In [1]:
import pandas as pd
d=pd.read_csv('/content/Advertising.csv')
print(d)

     Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]


In [2]:
y=d['Sales']
x=d.drop(['Sales','Unnamed: 0'],axis=1)

In [3]:
x=d.drop(['Sales','Unnamed: 0'],axis=1)
print(x)

        TV  Radio  Newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]


In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [5]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, mean_absolute_percentage_error,root_mean_squared_error
from sklearn.linear_model import LinearRegression
model_lr = LinearRegression()
model_lr.fit(x_train, y_train)


LinearRegression()

In [6]:
y_pred_train = model_lr.predict(x_train)
y_pred_test= model_lr.predict(x_test)
print(f'train data MSE score LR: {mean_squared_error(y_train,y_pred_train )}')
print(f'train data MAE score LR: {mean_absolute_error(y_train, y_pred_train)}')

train data MSE score LR: 2.5274986530805155
train data MAE score LR: 1.246270576902696


In [7]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(d, test_size = 0.2)

In [8]:
from sklearn.svm import SVR
model_svr = SVR()
model_svr.fit(x_train, y_train)

SVR()

In [9]:
from sklearn.svm import SVR
model_svr = SVR()
model_svr.fit(x_train, y_train)
y_pred_train = model_svr.predict(x_train)
y_pred_test= model_svr.predict(x_test)
print(f'train data MSE score SVR: {mean_squared_error(y_train,y_pred_train )}')
print(f'train data MAE score SVR: {mean_absolute_error(y_train, y_pred_train)}')
print(f'train data RMSE score SVR: {root_mean_squared_error(y_train,y_pred_train )}')
print()
print(f'test data MSE score SVR: {mean_squared_error(y_test, y_pred_test)}')
print(f'test data MAE score SVR: {mean_absolute_error(y_test, y_pred_test)}')
print(f'test data RMSE score SVR: {root_mean_squared_error(y_test, y_pred_test)}')
print()

train data MSE score SVR: 3.9152465151093354
train data MAE score SVR: 1.436320050942347
train data RMSE score SVR: 1.9786981869677183

test data MSE score SVR: 3.7626669223061304
test data MAE score SVR: 1.3781138611493062
test data RMSE score SVR: 1.9397595011511428



In [10]:
y_pred_train = model_lr.predict(x_train)
y_pred_test= model_lr.predict(x_test)

In [11]:
from sklearn.linear_model import Lasso, Ridge
model_lasso = Lasso(alpha=1.0)
model_lasso.fit(x_train, y_train)
model_ridge = Ridge(alpha=1.0)
model_ridge.fit(x_train, y_train)
y_pred_lasso = model_lasso.predict(x_test)
y_pred_ridge = model_ridge.predict(x_test)
y_pred_lasso1 = model_lasso.predict(x_train)
y_pred_ridge1 = model_ridge.predict(x_train)
print(f'test data MSE score lasso: {mean_squared_error(y_test,y_pred_lasso)}')
print(f'test data MAE score lasso: {mean_absolute_error(y_test, y_pred_lasso)}')
print(f'test data RMSE score lasso: {root_mean_squared_error(y_test, y_pred_lasso)}')
print()
print(f'train data MSE score lasso: {mean_squared_error(y_train,y_pred_lasso1)}')
print(f'train data MAE score lasso: {mean_absolute_error(y_train,y_pred_lasso1 )}')
print(f'train data RMSE score lasso: {root_mean_squared_error(y_train,y_pred_lasso1)}')
print()

test data MSE score lasso: 3.81354534785588
test data MAE score lasso: 1.290244367363744
test data RMSE score lasso: 1.9528300867858115

train data MSE score lasso: 2.537205574035216
train data MAE score lasso: 1.2500538064977016
train data RMSE score lasso: 1.5928608143950356



In [12]:
from sklearn.linear_model import Lasso, Ridge
model_lasso = Lasso(alpha=1.0)
model_lasso.fit(x_train, y_train)

Lasso()

In [13]:
from sklearn.linear_model import Lasso, Ridge
model_ridge = Ridge(alpha=1.0)
model_ridge.fit(x_train, y_train)

Ridge()

In [14]:
print(f'train data MSE score ridge: {mean_squared_error(y_train,y_pred_ridge1)}')
print(f'train data MAE score ridge: {mean_absolute_error(y_train,y_pred_ridge1 )}')
print(f'train data RMSE score ridge: {root_mean_squared_error(y_train,y_pred_ridge1)}')
print()
print(f'test data MSE score ridge: {mean_squared_error(y_test,y_pred_ridge)}')
print(f'test data MAE score ridge: {mean_absolute_error(y_test,y_pred_ridge )}')
print(f'test data RMSE score ridge: {root_mean_squared_error(y_test,y_pred_ridge)}')
print()

train data MSE score ridge: 2.527498660478399
train data MAE score ridge: 1.2462730109842535
train data RMSE score ridge: 1.5898108882752058

test data MSE score ridge: 3.9130332250056528
test data MAE score ridge: 1.3007809605982446
test data RMSE score ridge: 1.9781388285470898



In [15]:
x_train = train.iloc[:, :20].values
x_test = test.iloc[:, :20].values
y_train = train.iloc[:, -1].values
y_test = test.iloc[:, -1].values
print(x_train)
print()
print(x_test)
print()
print(y_test)

[[ 22.  237.4   5.1  23.5  12.5]
 [163.  188.4  18.1  25.6  14.9]
 [106.  137.9  46.4  59.   19.2]
 [192.   75.5  10.8   6.    9.9]
 [174.  168.4   7.1  12.8  11.7]
 [121.  141.3  26.8  46.2  15.5]
 [ 67.   31.5  24.6   2.2   9.5]
 [122.   18.8  21.7  50.4   7. ]
 [157.   93.9  43.5  50.5  15.3]
 [184.  287.6  43.   71.8  26.2]
 [ 69.  237.4  27.5  11.   18.9]
 [182.  218.5   5.4  27.4  12.2]
 [ 42.  177.   33.4  38.7  17.1]
 [ 52.  100.4   9.6   3.6  10.7]
 [ 43.  293.6  27.7   1.8  20.7]
 [102.  296.4  36.3 100.9  23.8]
 [ 15.  204.1  32.9  46.   19. ]
 [ 59.  210.8  49.6  37.7  23.8]
 [112.  241.7  38.   23.2  21.8]
 [ 95.  107.4  14.   10.9  11.5]
 [144.  104.6   5.7  34.4  10.4]
 [131.    0.7  39.6   8.7   1.6]
 [124.  123.1  34.6  12.4  15.2]
 [188.  191.1  28.7  18.2  17.3]
 [145.   96.2  14.8  38.9  11.4]
 [181.  156.6   2.6   8.3  10.5]
 [197.   94.2   4.9   8.1   9.7]
 [194.  166.8  42.    3.6  19.6]
 [  6.    8.7  48.9  75.    7.2]
 [103.  280.2  10.1  21.4  14.8]
 [ 12.  21

In [16]:
from sklearn.neighbors import KNeighborsRegressor
model_knn = KNeighborsRegressor(n_neighbors=5)
model_knn.fit(x_train, y_train)

KNeighborsRegressor()

In [17]:
y_pred_train = model_knn.predict(x_train)
y_pred_test = model_knn.predict(x_test)
print(f'train data MSE score KNN: {mean_squared_error(y_train,y_pred_train )}')
print(f'train data MAE score KNN: {mean_absolute_error(y_train, y_pred_train)}')

train data MSE score KNN: 3.3988074999999993
train data MAE score KNN: 1.3908749999999999


In [18]:
import numpy as np
from sklearn.utils import resample
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error

def bootstrap_metrics(model, x_train, y_train, x_test, y_test, n_iterations=10):
    mse_values = []
    mae_values = []
    rmse_values = []
    for _ in range(n_iterations):
        x_train_resampled, y_train_resampled = resample(x_train, y_train)
        model.fit(x_train_resampled, y_train_resampled)
        y_pred = model.predict(x_test)
        mse_values.append(mean_squared_error(y_test, y_pred))
        mae_values.append(mean_absolute_error(y_test, y_pred))
        rmse_values.append(root_mean_squared_error(y_test, y_pred))
    return np.array(mse_values), np.array(mae_values), np.array(rmse_values)

mse_lr, mae_lr, rmse_lr = bootstrap_metrics(model_lr, x_train, y_train, x_test, y_test)


print(f"Bootstrapped MSE for Linear Regression: {mse_lr.mean()}")
print(f"Confidence intervals for Linear Regression MSE: {np.percentile(mse_lr, [2.5, 97.5])}")
print(f"Bootstrapped MAE for Linear Regression: {mae_lr.mean()}")
print(f"Confidence intervals for Linear Regression MAE: {np.percentile(mae_lr, [2.5, 97.5])}")
print(f"Bootstrapped RMSE for Linear Regression: {rmse_lr.mean()}")
print(f"Confidence intervals for Linear Regression RMSE: {np.percentile(rmse_lr, [2.5, 97.5])}")

Bootstrapped MSE for Linear Regression: 5.166447283518711e-29
Confidence intervals for Linear Regression MSE: [5.04525853e-30 1.29978639e-28]
Bootstrapped MAE for Linear Regression: 5.437872374614017e-15
Confidence intervals for Linear Regression MAE: [1.60704783e-15 1.01751940e-14]
Bootstrapped RMSE for Linear Regression: 6.521431858432515e-15
Confidence intervals for Linear Regression RMSE: [2.23372102e-15 1.13844660e-14]


In [19]:
import numpy as np
from sklearn.utils import resample
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error

def bootstrap_metrics_svr(model, x_train, y_train, x_test, y_test, n_iterations=10):
    mse_values = []
    mae_values = []
    rmse_values = []
    for _ in range(n_iterations):

        x_train_resampled, y_train_resampled = resample(x_train, y_train)

        model.fit(x_train_resampled, y_train_resampled)

        y_pred = model.predict(x_test)

        mse_values.append(mean_squared_error(y_test, y_pred))
        mae_values.append(mean_absolute_error(y_test, y_pred))
        rmse_values.append(root_mean_squared_error(y_test, y_pred))
    return np.array(mse_values), np.array(mae_values), np.array(rmse_values)


mse_svr, mae_svr, rmse_svr = bootstrap_metrics_svr(model_svr, x_train, y_train, x_test, y_test)

print(f"Bootstrapped MSE for SVR: {mse_svr.mean()}")
print(f"Confidence intervals for SVR MSE: {np.percentile(mse_svr, [2.5, 97.5])}")
print(f"Bootstrapped MAE for SVR: {mae_svr.mean()}")
print(f"Confidence intervals for SVR MAE: {np.percentile(mae_svr, [2.5, 97.5])}")
print(f"Bootstrapped RMSE for SVR: {rmse_svr.mean()}")
print(f"Confidence intervals for SVR RMSE: {np.percentile(rmse_svr, [2.5, 97.5])}")

Bootstrapped MSE for SVR: 5.428775431640028
Confidence intervals for SVR MSE: [4.82383137 6.36973904]
Bootstrapped MAE for SVR: 1.8632133492928393
Confidence intervals for SVR MAE: [1.72957396 2.02999501]
Bootstrapped RMSE for SVR: 2.327705641798059
Confidence intervals for SVR RMSE: [2.19627813 2.52358425]


In [20]:
import numpy as np
from sklearn.utils import resample
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error

def bootstrap_metrics_svr(model, x_train, y_train, x_test, y_test, n_iterations=10):
    mse_values = []
    mae_values = []
    rmse_values = []
    for _ in range(n_iterations):

        x_train_resampled, y_train_resampled = resample(x_train, y_train)

        model.fit(x_train_resampled, y_train_resampled)

        y_pred = model.predict(x_test)

        mse_values.append(mean_squared_error(y_test, y_pred))
        mae_values.append(mean_absolute_error(y_test, y_pred))
        rmse_values.append(root_mean_squared_error(y_test, y_pred))
    return np.array(mse_values), np.array(mae_values), np.array(rmse_values)


mse_svr, mae_svr, rmse_svr = bootstrap_metrics_svr(model_svr, x_train, y_train, x_test, y_test)

print(f"Bootstrapped MSE for SVR: {mse_svr.mean()}")
print(f"Confidence intervals for SVR MSE: {np.percentile(mse_svr, [2.5, 97.5])}")
print(f"Bootstrapped MAE for SVR: {mae_svr.mean()}")
print(f"Confidence intervals for SVR MAE: {np.percentile(mae_svr, [2.5, 97.5])}")
print(f"Bootstrapped RMSE for SVR: {rmse_svr.mean()}")
print(f"Confidence intervals for SVR RMSE: {np.percentile(rmse_svr, [2.5, 97.5])}")

Bootstrapped MSE for SVR: 5.551695459886376
Confidence intervals for SVR MSE: [5.02671461 6.2630672 ]
Bootstrapped MAE for SVR: 1.8665954992923315
Confidence intervals for SVR MAE: [1.76481315 2.01370224]
Bootstrapped RMSE for SVR: 2.3546121003795846
Confidence intervals for SVR RMSE: [2.24202743 2.50246877]


In [21]:
import numpy as np
from sklearn.utils import resample
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error

def bootstrap_metrics_svr(model, x_train, y_train, x_test, y_test, n_iterations=10):
    mse_values = []
    mae_values = []
    rmse_values = []
    for _ in range(n_iterations):

        x_train_resampled, y_train_resampled = resample(x_train, y_train)

        model.fit(x_train_resampled, y_train_resampled)

        y_pred = model.predict(x_test)

        mse_values.append(mean_squared_error(y_test, y_pred))
        mae_values.append(mean_absolute_error(y_test, y_pred))
        rmse_values.append(root_mean_squared_error(y_test, y_pred))
    return np.array(mse_values), np.array(mae_values), np.array(rmse_values)


mse_svr, mae_svr, rmse_svr = bootstrap_metrics_svr(model_svr, x_train, y_train, x_test, y_test)

print(f"Bootstrapped MSE for SVR: {mse_svr.mean()}")
print(f"Confidence intervals for SVR MSE: {np.percentile(mse_svr, [2.5, 97.5])}")
print(f"Bootstrapped MAE for SVR: {mae_svr.mean()}")
print(f"Confidence intervals for SVR MAE: {np.percentile(mae_svr, [2.5, 97.5])}")
print(f"Bootstrapped RMSE for SVR: {rmse_svr.mean()}")
print(f"Confidence intervals for SVR RMSE: {np.percentile(rmse_svr, [2.5, 97.5])}")

Bootstrapped MSE for SVR: 5.3647865514738715
Confidence intervals for SVR MSE: [4.78252364 6.11953523]
Bootstrapped MAE for SVR: 1.8569340952175835
Confidence intervals for SVR MAE: [1.76112349 1.97072155]
Bootstrapped RMSE for SVR: 2.314579117658908
Confidence intervals for SVR RMSE: [2.18663834 2.47334586]


In [22]:
import numpy as np
from sklearn.utils import resample
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error

def bootstrap_metrics_svr(model, x_train, y_train, x_test, y_test, n_iterations=10):
    mse_values = []
    mae_values = []
    rmse_values = []
    for _ in range(n_iterations):

        x_train_resampled, y_train_resampled = resample(x_train, y_train)

        model.fit(x_train_resampled, y_train_resampled)

        y_pred = model.predict(x_test)

        mse_values.append(mean_squared_error(y_test, y_pred))
        mae_values.append(mean_absolute_error(y_test, y_pred))
        rmse_values.append(root_mean_squared_error(y_test, y_pred))
    return np.array(mse_values), np.array(mae_values), np.array(rmse_values)


mse_svr, mae_svr, rmse_svr = bootstrap_metrics_svr(model_svr, x_train, y_train, x_test, y_test)

print(f"Bootstrapped MSE for SVR: {mse_svr.mean()}")
print(f"Confidence intervals for SVR MSE: {np.percentile(mse_svr, [2.5, 97.5])}")
print(f"Bootstrapped MAE for SVR: {mae_svr.mean()}")
print(f"Confidence intervals for SVR MAE: {np.percentile(mae_svr, [2.5, 97.5])}")
print(f"Bootstrapped RMSE for SVR: {rmse_svr.mean()}")
print(f"Confidence intervals for SVR RMSE: {np.percentile(rmse_svr, [2.5, 97.5])}")

Bootstrapped MSE for SVR: 5.721931898407767
Confidence intervals for SVR MSE: [5.00352461 6.6458533 ]
Bootstrapped MAE for SVR: 1.8851655687679272
Confidence intervals for SVR MAE: [1.72854409 2.06427089]
Bootstrapped RMSE for SVR: 2.389858482653347
Confidence intervals for SVR RMSE: [2.23667443 2.57787486]


In [23]:
import numpy as np
from sklearn.utils import resample
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error

In [24]:
def bootstrap_metrics_knn(model, x_train, y_train, x_test, y_test, n_iterations=10):
    mse_values = []
    mae_values = []
    rmse_values = []
    for _ in range(n_iterations):

        x_train_resampled, y_train_resampled = resample(x_train, y_train)

        model.fit(x_train_resampled, y_train_resampled)

        y_pred = model.predict(x_test)

        mse_values.append(mean_squared_error(y_test, y_pred))
        mae_values.append(mean_absolute_error(y_test, y_pred))
        rmse_values.append(root_mean_squared_error(y_test, y_pred))

    return np.array(mse_values), np.array(mae_values), np.array(rmse_values)

In [25]:
mse_knn, mae_knn, rmse_knn = bootstrap_metrics_knn(model_knn, x_train, y_train, x_test, y_test)

print(f"Bootstrapped MSE for KNN Regression: {mse_knn.mean()}")
print(f"Confidence intervals for KNN Regression MSE: {np.percentile(mse_knn, [2.5, 97.5])}")
print(f"Bootstrapped MAE for KNN Regression: {mae_knn.mean()}")
print(f"Confidence intervals for KNN Regression MAE: {np.percentile(mae_knn, [2.5, 97.5])}")
print(f"Bootstrapped RMSE for KNN Regression: {rmse_knn.mean()}")
print(f"Confidence intervals for KNN Regression RMSE: {np.percentile(rmse_knn, [2.5, 97.5])}")

Bootstrapped MSE for KNN Regression: 8.248074
Confidence intervals for KNN Regression MSE: [6.16699125 9.86596525]
Bootstrapped MAE for KNN Regression: 2.3284000000000002
Confidence intervals for KNN Regression MAE: [2.0784125 2.5592375]
Bootstrapped RMSE for KNN Regression: 2.8643776612653022
Confidence intervals for KNN Regression RMSE: [2.48275427 3.1405976 ]
